### ISSUE TITLE
transfer to jump-dev?

### ISSUE THREAD

**Issue by mlubin** [jump-dev/NLopt.jl#147]
@stevengj, we're moving repositories out from JuliaOpt and into [jump-dev](https://github.com/jump-dev), an organization more explicitly centered around JuMP. JuliaOpt will become an obsolete organization. While we'd be happy for the jump-dev org to be the home for NLopt.jl, for better or worse there's currently minimal overlap between JuMP developers and active contributors to this repository, and moving the repository into jump-dev has some branding implications worth considering (given how NLopt is easily usable without JuMP). What are your thoughts on where this repository should be hosted?

**Comment by stevengj** [comment]
I don't have any strong opinions on hosting, but since I don't use JuMP myself I haven't had time to work on keeping the JuMP integration up to date.

**Comment by blegat** [comment]
We are checking that NLopt continues to pass MOI tests with [SolverTests] (https://github.com/blegat/SolverTests/blob/29854a4abb14182f099520b32085cef6f08448e9/.travis.yml#L35) before any new release of MOI so it should work fine with JuMP

**Comment by stevengj** [comment]
That's good to hear.

As I said, I don't have strong opinions on which org this should be in, but I suppose if jump-dev has more active developers then moving this might make sense.

**Comment by odow** [comment]
Any more thoughts on this? It seems to be doing okay here, but it's the only repo left in JuliaOpt that is active

**Comment by odow** [comment]
I think this would be useful to move to JuMP-dev from a developer/maintenance perspective. (More visibility, it'd show up in my default notifications, etc)

But I understand the not wanting to become too attached to the JuMP brand when it can (and perhaps should) be used separately.

**Comment by blegat** [comment]
I don't think the jump-dev org is about what is used with JuMP but it's more about what is maintained by the JuMP developers. As a matter of fact, many solvers used with JuMP are not in the JuMP org

**Comment by odow** [comment]
Somewhat related. I've updated the README to deprioritize mentions of JuMP and MOI. Previously, `using with MathOptInterface` came before the basic tutorial: https://github.com/JuliaOpt/NLopt.jl/tree/v1.0.3?tab=readme-ov-file#using-with-mathoptinterface

**Comment by odow** [comment]
The conclusion of the monthly developer call was that there was no point keeping NLopt in an obsolete organization, and that the JuMP developers are happy to take over long-term maintenance of NLopt.jl. 

I've moved this to `jump-dev` and sent @stevengj an invite for admin access.
