### ISSUE TITLE
Mention important bug in README

### ISSUE THREAD

**Issue by matthewelmer-tamu** [jump-dev/NLopt.jl#248]
After having wasted a bunch of time on [this bug](https://github.com/stevengj/nlopt/issues/57), I figured that it should be mentioned prominently somewhere within the README so that others do not suffer the same fate.

**Comment by odow** [comment]
There are 117 open issues in https://github.com/stevengj/nlopt. I don't know if the Julia wrapper is the correct place to call out individual upstream issues.

Note that bugs like this are not uncommon. Check out the list of bug fixes in Gurobi (an expensive commercial best-inn-class MIP solver: https://www.gurobi.com/downloads/recent-bug-fixes-by-version/).

**Comment by odow** [comment]
I'm going to close this as won't fix. But if you feel strongly, please open a pull request with your suggested wording.
